In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
!pip install seaborn
import seaborn as sns

[notice] A new release of pip is available: 26.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: seaborn in c:\users\karti\anaconda3\envs\dl_env\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\karti\anaconda3\envs\dl_env\lib\site-packages (from seaborn) (2.0.1)
Requirement already satisfied: pandas>=1.2 in c:\users\karti\anaconda3\envs\dl_env\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\karti\anaconda3\envs\dl_env\lib\site-packages (from seaborn) (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\karti\anaconda3\envs\dl_env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\karti\anaconda3\envs\dl_env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\karti\anaconda3\envs\dl_env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\karti\anaconda3\envs\dl_env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\karti\anaconda3\envs\dl_env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\karti\anaconda3\envs\dl_env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.1.0)
Requirement already satisfied: pyparsing>=3 in c:\users\karti\anaconda3\envs\dl_env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\karti\anaconda3\envs\dl_env\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\karti\anaconda3\envs\dl_env\lib\site-packages (from pandas>=1.2->seaborn) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\karti\anaconda3\envs\dl_env\lib\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\karti\anaconda3\envs\dl_env\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

In [5]:
df = pd.read_csv("drug_side_effects_100k_dataset.csv")

In [6]:
df.head()

,patient_id,age,gender,country,drug_name,dosage_mg,side_effect,severity,outcome,report_date,treatment_start_date,chronic_condition,smoker,alcohol_use,hospitalized,recovery_days
0,PT-100000,56,Female,USA,Atorvastatin,25,Muscle Pain,Moderate,Recovering,2021-12-08,2021-11-23,Hypertension,Yes,Frequent,No,36.0
1,PT-100001,45,Male,USA,Sertraline,5,Dry Mouth,Mild,Recovered,2023-02-10,2023-02-04,Hypertension,Yes,Frequent,No,40.0
2,PT-100002,76,Female,Pakistan,Insulin,25,Hypoglycemia,Mild,Recovering,2021-07-30,2021-07-01,Heart Disease,No,NaN,No,12.0
3,PT-100003,61,Female,USA,Paracetamol,20,Rash,Moderate,Recovered,2025-05-02,2025-04-18,Asthma,Yes,NaN,No,26.0
4,PT-100004,39,Female,India,Amlodipine,5,Dizziness,Mild,Recovered,2025-05-23,2025-04-06,NaN,Yes,Occasional,No,7.0

In [7]:
df.shape

(100000, 16)

In [8]:
df['drug_name'].unique()

array(['Atorvastatin', 'Sertraline', 'Insulin', 'Paracetamol',
       'Amlodipine', 'Amoxicillin', 'Ibuprofen', 'Metformin',
       'Lisinopril', 'Omeprazole'], dtype=object)

In [9]:
df['country'].unique()

array(['USA', 'Pakistan', 'India', 'Australia', 'UK', 'Canada', 'Germany'],
      dtype=object)

In [ ]:
df['side_effect'].unique()

array(['Muscle Pain', 'Dry Mouth', 'Hypoglycemia', 'Rash', 'Dizziness',
       'Nausea', 'Sweating', 'Swelling', 'Anxiety', 'Stomach Pain',
       'Abdominal Pain', 'Headache', 'Fatigue', 'Weight Gain',
       'Heartburn', 'Diarrhea', 'Dry Cough', 'Constipation',
       'Liver Toxicity', 'Palpitations', 'Insomnia'], dtype=object)

In [ ]:
df["chronic_condition"].unique()

array(['Hypertension', 'Heart Disease', 'Asthma', nan, 'Diabetes',
       'Kidney Disease'], dtype=object)

In [11]:
df["outcome"].unique()

array(['Recovering', 'Recovered', 'Hospitalized', 'Fatal'], dtype=object)

In [ ]:
df["severity"].unique()

array(['Moderate', 'Mild', 'Severe'], dtype=object)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   patient_id            100000 non-null  object
 1   age                   100000 non-null  int64
 2   gender                100000 non-null  object
 3   country               100000 non-null  object
 4   drug_name             100000 non-null  object
 5   dosage_mg             100000 non-null  int64
 6   side_effect           100000 non-null  object
 7   severity              100000 non-null  object
 8   outcome               100000 non-null  object
 9   report_date           100000 non-null  object
 10  treatment_start_date  100000 non-null  object
 11  chronic_condition     83257 non-null   object
 12  smoker                100000 non-null  object
 13  alcohol_use           66635 non-null   object
 14  hospitalized          100000 non-null  object
 15  recovery_days         88262 non-null   float64
dtypes: float64(1), int64(2), object(13)
memory usage: 12.2+ MB

In [ ]:
df.describe()

                 age      dosage_mg  recovery_days
count  100000.000000  100000.000000   88262.000000
mean       47.781740     119.896250      23.569996
std        17.055106     162.249791      12.690178
min        18.000000       5.000000       2.000000
25%        35.000000      10.000000      13.000000
50%        47.000000      25.000000      24.000000
75%        60.000000     250.000000      35.000000
max        90.000000     500.000000      45.000000

In [ ]:
df.isnull().sum()

patient_id                  0
age                         0
gender                      0
country                     0
drug_name                   0
dosage_mg                   0
side_effect                 0
severity                    0
outcome                     0
report_date                 0
treatment_start_date        0
chronic_condition       16743
smoker                      0
alcohol_use             33365
hospitalized                0
recovery_days           11738
dtype: int64

In [ ]:
df.drop(["patient_id", "report_date", "treatment_start_date"], axis=1, inplace=True)

In [ ]:
df.head()

,age,gender,country,drug_name,dosage_mg,side_effect,severity,outcome,chronic_condition,smoker,alcohol_use,hospitalized,recovery_days
0,56,Female,USA,Atorvastatin,25,Muscle Pain,Moderate,Recovering,Hypertension,Yes,Frequent,No,36.0
1,45,Male,USA,Sertraline,5,Dry Mouth,Mild,Recovered,Hypertension,Yes,Frequent,No,40.0
2,76,Female,Pakistan,Insulin,25,Hypoglycemia,Mild,Recovering,Heart Disease,No,NaN,No,12.0
3,61,Female,USA,Paracetamol,20,Rash,Moderate,Recovered,Asthma,Yes,NaN,No,26.0
4,39,Female,India,Amlodipine,5,Dizziness,Mild,Recovered,NaN,Yes,Occasional,No,7.0

In [ ]:
df.duplicated().sum()

np.int64(9)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(0)